(2) Build CRUD by using json schema
InfyOmLabs/generator-builder pull request #34
Opened 2019-04-11 10:14 UTC by vishalinfyom

2019-04-12 06:03 UTC, farhaninfyom approved these changes

2019-04-12 06:56 UTC, ajayinfyom approved these changes

2019-04-13 10:59 UTC, mitulgolakiya requested changes

2019-04-13 10:59 UTC, mitulgolakiya commented on templates/routes.stub
> +Route::post('generator_builder/load-schema', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@loadSchema');
`generate-from-file`

2019-04-13 10:59 UTC, mitulgolakiya commented on src/Controllers/GeneratorBuilderController.php
> +            '--forceMigrate' => true,
use skip

2019-04-13 12:06 UTC, ajayinfyom approved these changes

2019-04-13 12:07 UTC, farhaninfyom approved these changes

2019-05-16 03:29 UTC, mitulgolakiya approved these changes

2019-05-16 03:29 UTC, merged